/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconBxCaretRight: typeof import('~icons/bx/caret-right')['default']
    'IconCryptocurrencyColor:bch': typeof import('~icons/cryptocurrency/bch')['default']
    'IconLa:ambulance': typeof import('~icons/la/ambulance')['default']
    'IconLogos:youtube': typeof import('~icons/logos/youtube')['default']
    IconLogosIntel: typeof import('~icons/logos/intel')['default']
    IconLogosMicrosoftWindows: typeof import('~icons/logos/microsoft-windows')['default']
    'IconSvgSpinners:tadpole': typeof import('~icons/svg-spinners/tadpole')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
